name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Update mingw-w64-x86_64-crt-git to 9.0.0.6373.5be8fcd83-2
      run: |
        $origPath = $env:PATH
        $env:PATH = "C:\msys64\mingw64\bin;C:\msys64\usr\bin;$origPath"
        pacman.exe -Syy
        pacman.exe -S --noconfirm --noprogressbar mingw-w64-x86_64-crt-git
        pacman.exe -Qi mingw-w64-x86_64-crt-git

    - name: Install dependencies
      run: |
        cabal update
        cabal install haskell-say

    - name: Build
      run: cabal build

    - name: Run 
      run: cabal run
