name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        cabal update
        cabal install haskell-say

    - name: Build
      run: cabal build

    - name: Run 
      run: cabal run
